# Generated by Django 2.2.3 on 2021-03-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0002_auto_20210309_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
