# Generated by Django 2.2.3 on 2021-03-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0004_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Teams',
        ),
    ]
