# Generated by Django 2.2.3 on 2021-03-10 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0005_auto_20210309_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('members', models.ManyToManyField(blank=True, to='bug.Profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'level': 'manager'}, on_delete=django.db.models.deletion.CASCADE, to='bug.Profile'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_deadline',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bug.Team'),
        ),
    ]
