# Generated by Django 2.2.3 on 2021-03-10 21:16

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0006_auto_20210310_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignee',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='project.team', chained_model_field='project.team', default=None, on_delete=django.db.models.deletion.CASCADE, to='bug.Profile'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bug.Project'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'level': 'standard'}, to='bug.Profile'),
        ),
    ]
