# Generated by Django 2.2.3 on 2021-03-10 21:18

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0007_auto_20210310_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignee',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='project', chained_model_field='project', default=None, on_delete=django.db.models.deletion.CASCADE, to='bug.Team'),
        ),
    ]
