# Generated by Django 2.2.3 on 2021-03-10 21:46

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0009_auto_20210310_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='To Do', max_length=240),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_member',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='assigned_team', chained_model_field='assigned_team', default=None, on_delete=django.db.models.deletion.CASCADE, to='bug.Profile'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_team',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='project', chained_model_field='project', on_delete=django.db.models.deletion.CASCADE, to='bug.Team'),
        ),
    ]
