# Generated by Django 2.2.3 on 2021-03-11 19:51

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0010_auto_20210310_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'level': 'standard'}, related_name='members', to='bug.Profile'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_member',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='assigned_team', chained_model_field='assigned_team', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_member', to='bug.Team'),
        ),
    ]
