# Generated by Django 2.2.3 on 2021-03-11 22:21

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0011_auto_20210311_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_member',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='ticket_team', chained_model_field='team', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_member', to='bug.Profile'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bug.Team'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_member',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='assigned_team', chained_model_field='team', on_delete=django.db.models.deletion.CASCADE, to='bug.Profile'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_team',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='project', chained_model_field='project', on_delete=django.db.models.deletion.CASCADE, related_name='t_team', to='bug.Team'),
        ),
    ]
